#!/bin/sh

#    check whether somebody requested a reboot of that machine
#
#    Copyright (C) 2015  Thorsten Alteholz
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation in version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# due to systemd and probably private /tmp, this needs to be somewhere else
STAMPFILE=/usr/local/nagios/reboot-needed

if [ -f $STAMPFILE ]; then
  echo "CRITICAL - reboot requested"
  exit 2
fi

echo "OK - no reboot requested"

exit 0
